-- ============================================================================
-- COMPLETE DATA MIGRATION SQL - FIXED SYNTAX
-- MOKO Furniture Store - Moving all hardcoded data to database
-- ============================================================================

-- Clear existing data
DELETE FROM products;

-- ============================================================================
-- SOFAS - Complete product data migration
-- ============================================================================
INSERT INTO products (title, slug, price, price_range, image, images, category, description, features, dimensions, whats_good, related) VALUES
-- Mr Biggie Series
('Mr Biggie 5-seater Sofa', 'mr-biggie-5-seater-sofa', 'KSh 35,798', 'KSh 35,798 – KSh 39,148', 'https://cdn.shortpixel.ai/spai/w_433+q_lossy+ret_img+to_webp/moko.co.ke/wp-content/uploads/2024/08/HUM_9636-1-1-500x500.jpg', ARRAY['https://cdn.shortpixel.ai/spai/w_433+q_lossy+ret_img+to_webp/moko.co.ke/wp-content/uploads/2024/08/HUM_9636-1-1-500x500.jpg'], 'Sofas', 'Mr Biggie 5-seater sofa has modern design that''s built to last. It''s big, spacious and curvy with sturdy construction.', ARRAY['Curvy modern design', 'Extra 20cm per seat for comfort', 'Firm foam seats', 'Sturdy construction', 'Easy assembly'], ARRAY['Width: 850mm', 'Height: 820mm', 'Length: 2410mm'], ARRAY['Perfect for large families', 'Modern curvy design', 'Built to last', 'Extra spacious seating'], ARRAY['jiji-5-seater-sofa-kutana-table', 'jiji-6-seater-sofa-footstool', 'queen-size-moko-mattress']),

('Mr Biggie 3-seater Sofa', 'mr-biggie-3-seater-sofa', 'KSh 20,949', 'KSh 20,949 – KSh 22,499', 'https://cdn.shortpixel.ai/spai/w_433+q_lossy+ret_img+to_webp/moko.co.ke/wp-content/uploads/2022/09/HUM_8637-min-500x500.jpg', ARRAY['https://cdn.shortpixel.ai/spai/w_433+q_lossy+ret_img+to_webp/moko.co.ke/wp-content/uploads/2022/09/HUM_8637-min-500x500.jpg'], 'Sofas', 'Mr Biggie 3-seater sofa with modern design built to last. Spacious and curvy for ultimate comfort.', ARRAY['Modern curvy design', '20cm extra per seat', 'Firm foam construction', 'Sturdy frame', 'Long-lasting materials'], ARRAY['Width: 850mm', 'Height: 820mm', 'Length: 2410mm'], ARRAY['Perfect for families', 'Modern design', 'Built to last', 'Comfortable seating'], ARRAY['mr-biggie-2-seater-sofa', 'mr-biggie-1-seater-sofa', 'jiji-3-seater-sofa']),

('Mr Biggie 2-seater Sofa', 'mr-biggie-2-seater-sofa', 'KSh 15,449', 'KSh 15,449 – KSh 16,999', 'https://cdn.shortpixel.ai/spai/w_433+q_lossy+ret_img+to_webp/moko.co.ke/wp-content/uploads/2022/09/HUM_8639-min-500x500.jpg', ARRAY['https://cdn.shortpixel.ai/spai/w_433+q_lossy+ret_img+to_webp/moko.co.ke/wp-content/uploads/2022/09/HUM_8639-min-500x500.jpg'], 'Sofas', 'Mr Biggie 2-seater sofa with modern design built to last. Perfect for couples or smaller spaces.', ARRAY['Curvy modern design', 'Extra seating space', 'Firm foam seats', 'Sturdy construction', 'Easy maintenance'], ARRAY['Width: 850mm', 'Height: 820mm', 'Length: 1860mm'], ARRAY['Perfect for couples', 'Modern design', 'Built to last', 'Space efficient'], ARRAY['mr-biggie-1-seater-sofa', 'mr-biggie-3-seater-sofa', 'jiji-2-seater-sofa']),

('Mr Biggie 1-seater Sofa', 'mr-biggie-1-seater-sofa', 'KSh 10,949', 'KSh 10,949 – KSh 11,949', 'https://cdn.shortpixel.ai/spai/w_433+q_lossy+ret_img+to_webp/moko.co.ke/wp-content/uploads/2023/08/HUM_9605-500x500.jpg', ARRAY['https://cdn.shortpixel.ai/spai/w_433+q_lossy+ret_img+to_webp/moko.co.ke/wp-content/uploads/2023/08/HUM_9605-500x500.jpg'], 'Sofas', 'Mr Biggie 1-seater sofa perfect for single seating or as an addition to complete your sofa set.', ARRAY['Single seating perfection', 'Curvy modern design', 'Firm foam construction', 'Sturdy frame', 'Easy maintenance'], ARRAY['Width: 850mm', 'Height: 820mm', 'Length: 1256mm'], ARRAY['Perfect single seating', 'Modern design', 'Built to last', 'Versatile addition'], ARRAY['mr-biggie-2-seater-sofa', 'mr-biggie-3-seater-sofa', 'jiji-1-seater-sofa']),

-- Jiji Series
('Jiji 6 Seater Sofa with Footstool', 'jiji-6-seater-sofa-footstool', 'KSh 37,499', 'KSh 37,499 – KSh 40,199', 'https://cdn.shortpixel.ai/spai/w_330+q_lossy+ret_img+to_webp/moko.co.ke/wp-content/uploads/2020/10/HUM_9690-min-500x500.jpg', ARRAY['https://cdn.shortpixel.ai/spai/w_330+q_lossy+ret_img+to_webp/moko.co.ke/wp-content/uploads/2020/10/HUM_9690-min-500x500.jpg'], 'Sofas', 'Jiji 6 seater sectional sofa designed to be the social hub. Perfect for large gatherings with removable cushion covers.', ARRAY['Functional back design', 'Space-friendly layout', '9-inch foam cushions', 'Removable covers', 'Strong frame'], ARRAY['Width: 0.8M', 'Length: 3.2M'], ARRAY['Perfect for large gatherings', 'Space-friendly design', 'Easy maintenance', 'Built to last'], ARRAY['jiji-5-seater-sofa-kutana-table', 'jiji-6-seater-sofa-kutana-table', 'jiji-3-seater-sofa']),

('Jiji 5 Seater Sofa with Kutana Table', 'jiji-5-seater-sofa-kutana-table', 'KSh 31,499', 'KSh 31,499 – KSh 34,199', 'https://cdn.shortpixel.ai/spai/w_330+q_lossy+ret_img+to_webp/moko.co.ke/wp-content/uploads/2020/10/HUM_9690-min-500x500.jpg', ARRAY['https://cdn.shortpixel.ai/spai/w_330+q_lossy+ret_img+to_webp/moko.co.ke/wp-content/uploads/2020/10/HUM_9690-min-500x500.jpg'], 'Sofas', 'Jiji 5 seater sectional sofa with kutana table - social hub for your home.', ARRAY['Functional back design', 'Space-friendly layout', '9-inch foam cushions', 'Removable covers', 'Includes kutana table'], ARRAY['Width: 0.8M', 'Length: 2.4M'], ARRAY['Perfect for social gatherings', 'Includes kutana table', 'Space-friendly design', 'Easy maintenance'], ARRAY['jiji-6-seater-sofa-footstool', 'jiji-3-seater-sofa', 'jiji-2-seater-sofa']),

('Jiji 3 Seater Sofa', 'jiji-3-seater-sofa', 'KSh 31,499', 'KSh 31,499 – KSh 34,199', 'https://cdn.shortpixel.ai/spai/w_330+q_lossy+ret_img+to_webp/moko.co.ke/wp-content/uploads/2020/10/HUM_9690-min-500x500.jpg', ARRAY['https://cdn.shortpixel.ai/spai/w_330+q_lossy+ret_img+to_webp/moko.co.ke/wp-content/uploads/2020/10/HUM_9690-min-500x500.jpg'], 'Sofas', 'Jiji 3 seater sectional sofa designed as a social hub for your home. Accommodates more people without taking much space.', ARRAY['Functional back design', 'Space-friendly layout', '9-inch foam cushions', 'Removable covers', 'Strong frame'], ARRAY['Width: 0.8M', 'Length: 2.0M'], ARRAY['Perfect for families', 'Space-friendly design', 'Easy maintenance', 'Social hub design'], ARRAY['jiji-6-seater-sofa-footstool', 'jiji-6-seater-sofa-kutana-table', 'jiji-5-seater-sofa-kutana-table']),

('Jiji 2 Seater Sofa', 'jiji-2-seater-sofa', 'KSh 21,499', 'KSh 21,499 – KSh 24,299', 'https://cdn.shortpixel.ai/spai/w_330+q_lossy+ret_img+to_webp/moko.co.ke/wp-content/uploads/2020/10/jiji-2-seater-lifestyle.jpg', ARRAY['https://cdn.shortpixel.ai/spai/w_330+q_lossy+ret_img+to_webp/moko.co.ke/wp-content/uploads/2020/10/jiji-2-seater-lifestyle.jpg'], 'Sofas', 'Jiji 2 seater sectional sofa perfect for smaller spaces without compromising on comfort or style.', ARRAY['Functional back design', 'Space-friendly layout', '9-inch foam cushions', 'Removable covers', 'Strong frame'], ARRAY['Width: 0.8M', 'Length: 1.6M'], ARRAY['Perfect for couples', 'Space-friendly design', 'Easy maintenance', 'Compact yet comfortable'], ARRAY['jiji-3-seater-sofa', 'jiji-6-seater-sofa-footstool', 'mr-biggie-2-seater-sofa']),

-- ============================================================================
-- MATTRESSES - Complete product data migration
-- ============================================================================
INSERT INTO products (title, slug, price, price_range, image, images, category, description, features, dimensions, whats_good, related) VALUES
-- Moko Mattresses
('Queen Size Moko Mattress', 'queen-size-moko-mattress', 'KSh 13,999', 'KSh 13,999 – KSh 15,499', 'https://cdn.shortpixel.ai/spai/w_433+q_lossy+ret_img+to_webp/moko.co.ke/wp-content/uploads/2024/08/HUM_9636-1-1-500x500.jpg', ARRAY['https://cdn.shortpixel.ai/spai/w_433+q_lossy+ret_img+to_webp/moko.co.ke/wp-content/uploads/2024/08/HUM_9636-1-1-500x500.jpg'], 'Mattresses', 'Premium queen size moko mattress designed for ultimate comfort and support. Perfect balance of firmness and softness.', ARRAY['Premium comfort layers', 'Orthopedic support', 'Breathable fabric', 'Long-lasting materials', 'Hypoallergenic'], ARRAY['Width: 1520mm', 'Length: 1980mm', 'Height: 200mm'], ARRAY['Ultimate comfort', 'Orthopedic support', 'Long-lasting quality', 'Hypoallergenic materials'], ARRAY['king-size-moko-mattress', 'double-moko-mattress', 'single-moko-mattress']),

('King Size Moko Mattress', 'king-size-moko-mattress', 'KSh 17,999', 'KSh 17,999 – KSh 19,499', 'https://cdn.shortpixel.ai/spai/w_433+q_lossy+ret_img+to_webp/moko.co.ke/wp-content/uploads/2024/08/HUM_9636-1-1-500x500.jpg', ARRAY['https://cdn.shortpixel.ai/spai/w_433+q_lossy+ret_img+to_webp/moko.co.ke/wp-content/uploads/2024/08/HUM_9636-1-1-500x500.jpg'], 'Mattresses', 'Luxury king size moko mattress providing maximum space and comfort. Ideal for couples who value premium sleep quality.', ARRAY['Luxury comfort layers', 'Maximum support', 'Premium fabric', 'Durable construction', 'Temperature regulation'], ARRAY['Width: 1830mm', 'Length: 1980mm', 'Height: 200mm'], ARRAY['Maximum space', 'Premium comfort', 'Couples friendly', 'Temperature regulation'], ARRAY['queen-size-moko-mattress', 'double-moko-mattress', 'single-moko-mattress']),

('Double Moko Mattress', 'double-moko-mattress', 'KSh 11,999', 'KSh 11,999 – KSh 13,499', 'https://cdn.shortpixel.ai/spai/w_433+q_lossy+ret_img+to_webp/moko.co.ke/wp-content/uploads/2024/08/HUM_9636-1-1-500x500.jpg', ARRAY['https://cdn.shortpixel.ai/spai/w_433+q_lossy+ret_img+to_webp/moko.co.ke/wp-content/uploads/2024/08/HUM_9636-1-1-500x500.jpg'], 'Mattresses', 'Comfortable double moko mattress perfect for single sleepers or smaller bedrooms.', ARRAY['Comfort support layers', 'Space efficient', 'Quality materials', 'Affordable luxury', 'Easy maintenance'], ARRAY['Width: 1370mm', 'Length: 1880mm', 'Height: 200mm'], ARRAY['Space efficient', 'Single sleeper perfect', 'Quality materials', 'Affordable luxury'], ARRAY['queen-size-moko-mattress', 'single-moko-mattress', 'king-size-moko-mattress']),

('Single Moko Mattress', 'single-moko-mattress', 'KSh 8,999', 'KSh 8,999 – KSh 10,499', 'https://cdn.shortpixel.ai/spai/w_433+q_lossy+ret_img+to_webp/moko.co.ke/wp-content/uploads/2024/08/HUM_9636-1-1-500x500.jpg', ARRAY['https://cdn.shortpixel.ai/spai/w_433+q_lossy+ret_img+to_webp/moko.co.ke/wp-content/uploads/2024/08/HUM_9636-1-1-500x500.jpg'], 'Mattresses', 'Compact single moko mattress ideal for children, guests, or smaller spaces without compromising comfort.', ARRAY['Compact design', 'Child-friendly', 'Guest perfect', 'Quality construction', 'Space saving'], ARRAY['Width: 910mm', 'Length: 1880mm', 'Height: 200mm'], ARRAY['Compact design', 'Child friendly', 'Guest perfect', 'Space saving'], ARRAY['double-moko-mattress', 'queen-size-moko-mattress', 'king-size-moko-mattress']),

-- ============================================================================
-- BEDS - Complete product data migration
-- ============================================================================
INSERT INTO products (title, slug, price, price_range, image, images, category, description, features, dimensions, whats_good, related) VALUES
('Modern Queen Bed Frame', 'modern-queen-bed-frame', 'KSh 25,999', 'KSh 25,999 – KSh 27,499', 'https://cdn.shortpixel.ai/spai/w_433+q_lossy+ret_img+to_webp/moko.co.ke/wp-content/uploads/2024/08/HUM_9636-1-1-500x500.jpg', ARRAY['https://cdn.shortpixel.ai/spai/w_433+q_lossy+ret_img+to_webp/moko.co.ke/wp-content/uploads/2024/08/HUM_9636-1-1-500x500.jpg'], 'Beds', 'Modern queen bed frame combining style and functionality. Perfect centerpiece for contemporary bedrooms.', ARRAY['Modern design', 'Sturdy construction', 'Easy assembly', 'Headboard included', 'Under-bed storage'], ARRAY['Width: 1600mm', 'Length: 2050mm', 'Height: 1200mm'], ARRAY['Modern centerpiece', 'Sturdy construction', 'Storage solution', 'Easy assembly'], ARRAY['queen-size-moko-mattress', 'modern-king-bed-frame', 'modern-single-bed-frame']),

('Modern King Bed Frame', 'modern-king-bed-frame', 'KSh 32,999', 'KSh 32,999 – KSh 34,499', 'https://cdn.shortpixel.ai/spai/w_433+q_lossy+ret_img+to_webp/moko.co.ke/wp-content/uploads/2024/08/HUM_9636-1-1-500x500.jpg', ARRAY['https://cdn.shortpixel.ai/spai/w_433+q_lossy+ret_img+to_webp/moko.co.ke/wp-content/uploads/2024/08/HUM_9636-1-1-500x500.jpg'], 'Beds', 'Spacious modern king bed frame providing luxury and comfort for master bedrooms.', ARRAY['Luxury design', 'Maximum space', 'Premium materials', 'Easy maintenance', 'Headboard included'], ARRAY['Width: 1900mm', 'Length: 2050mm', 'Height: 1200mm'], ARRAY['Luxury master bedroom', 'Maximum space', 'Premium materials', 'Easy maintenance'], ARRAY['king-size-moko-mattress', 'modern-queen-bed-frame', 'modern-double-bed-frame']),

-- ============================================================================
-- CARPETS - Complete product data migration
-- ============================================================================
INSERT INTO products (title, slug, price, price_range, image, images, category, description, features, dimensions, whats_good, related) VALUES
('Modern Living Room Carpet', 'modern-living-room-carpet', 'KSh 7,999', 'KSh 7,999 – KSh 9,499', 'https://cdn.shortpixel.ai/spai/w_433+q_lossy+ret_img+to_webp/moko.co.ke/wp-content/uploads/2024/08/HUM_9636-1-1-500x500.jpg', ARRAY['https://cdn.shortpixel.ai/spai/w_433+q_lossy+ret_img+to_webp/moko.co.ke/wp-content/uploads/2024/08/HUM_9636-1-1-500x500.jpg'], 'Carpets', 'Modern living room carpet adding warmth and style to any space. Perfect for high-traffic areas.', ARRAY['Modern design', 'Durable materials', 'Easy cleaning', 'Non-slip backing', 'Stain resistant'], ARRAY['Width: 2000mm', 'Length: 3000mm', 'Thickness: 10mm'], ARRAY['Modern style', 'Durable materials', 'Easy cleaning', 'Non-slip safety'], ARRAY['modern-bedroom-carpet', 'modern-office-carpet', 'modern-dining-carpet']),

('Modern Bedroom Carpet', 'modern-bedroom-carpet', 'KSh 5,999', 'KSh 5,999 – KSh 7,499', 'https://cdn.shortpixel.ai/spai/w_433+q_lossy+ret_img+to_webp/moko.co.ke/wp-content/uploads/2024/08/HUM_9636-1-1-500x500.jpg', ARRAY['https://cdn.shortpixel.ai/spai/w_433+q_lossy+ret_img+to_webp/moko.co.ke/wp-content/uploads/2024/08/HUM_9636-1-1-500x500.jpg'], 'Carpets', 'Soft bedroom carpet providing comfort and warmth for bare feet. Perfect for creating cozy bedroom atmosphere.', ARRAY['Soft comfort', 'Bedroom perfect', 'Warm texture', 'Easy maintenance', 'Quality materials'], ARRAY['Width: 1600mm', 'Length: 2300mm', 'Thickness: 8mm'], ARRAY['Soft comfort', 'Bedroom perfect', 'Warm texture', 'Quality materials'], ARRAY['modern-living-room-carpet', 'modern-office-carpet', 'modern-children-carpet']),

-- ============================================================================
-- TV STANDS - Complete product data migration
-- ============================================================================
INSERT INTO products (title, slug, price, price_range, image, images, category, description, features, dimensions, whats_good, related) VALUES
('Modern TV Stand 55 inch', 'modern-tv-stand-55-inch', 'KSh 15,999', 'KSh 15,999 – KSh 17,499', 'https://cdn.shortpixel.ai/spai/w_433+q_lossy+ret_img+to_webp/moko.co.ke/wp-content/uploads/2024/08/HUM_9636-1-1-500x500.jpg', ARRAY['https://cdn.shortpixel.ai/spai/w_433+q_lossy+ret_img+to_webp/moko.co.ke/wp-content/uploads/2024/08/HUM_9636-1-1-500x500.jpg'], 'TV Stands', 'Modern TV stand accommodating up to 55-inch screens. Perfect blend of style and functionality.', ARRAY['Modern design', 'Cable management', 'Storage shelves', 'Easy assembly', 'Sturdy construction'], ARRAY['Width: 1200mm', 'Height: 500mm', 'Depth: 400mm'], ARRAY['Modern design', 'Cable management', 'Storage solution', 'Easy assembly'], ARRAY['modern-tv-stand-65-inch', 'modern-tv-stand-75-inch', 'modern-tv-stand-85-inch']),

('Modern TV Stand 65 inch', 'modern-tv-stand-65-inch', 'KSh 19,999', 'KSh 19,999 – KSh 21,499', 'https://cdn.shortpixel.ai/spai/w_433+q_lossy+ret_img+to_webp/moko.co.ke/wp-content/uploads/2024/08/HUM_9636-1-1-500x500.jpg', ARRAY['https://cdn.shortpixel.ai/spai/w_433+q_lossy+ret_img+to_webp/moko.co.ke/wp-content/uploads/2024/08/HUM_9636-1-1-500x500.jpg'], 'TV Stands', 'Spacious modern TV stand accommodating up to 65-inch screens. Perfect for larger entertainment setups.', ARRAY['Spacious design', 'Cable management', 'Multiple storage', 'Premium materials', 'Easy maintenance'], ARRAY['Width: 1500mm', 'Height: 500mm', 'Depth: 400mm'], ARRAY['Spacious design', 'Premium materials', 'Multiple storage', 'Easy maintenance'], ARRAY['modern-tv-stand-55-inch', 'modern-tv-stand-75-inch', 'modern-tv-stand-85-inch']),

('Modern TV Stand 75 inch', 'modern-tv-stand-75-inch', 'KSh 24,999', 'KSh 24,999 – KSh 26,499', 'https://cdn.shortpixel.ai/spai/w_433+q_lossy+ret_img+to_webp/moko.co.ke/wp-content/uploads/2024/08/HUM_9636-1-1-500x500.jpg', ARRAY['https://cdn.shortpixel.ai/spai/w_433+q_lossy+ret_img+to_webp/moko.co.ke/wp-content/uploads/2024/08/HUM_9636-1-1-500x500.jpg'], 'TV Stands', 'Large modern TV stand accommodating up to 75-inch screens. Perfect for home theater setups.', ARRAY['Large design', 'Premium materials', 'Advanced cable management', 'Multiple storage', 'Home theater ready'], ARRAY['Width: 1800mm', 'Height: 500mm', 'Depth: 400mm'], ARRAY['Large design', 'Home theater ready', 'Premium materials', 'Advanced cable management'], ARRAY['modern-tv-stand-65-inch', 'modern-tv-stand-55-inch', 'modern-tv-stand-85-inch']),

('Modern TV Stand 85 inch', 'modern-tv-stand-85-inch', 'KSh 29,999', 'KSh 29,999 – KSh 31,499', 'https://cdn.shortpixel.ai/spai/w_433+q_lossy+ret_img+to_webp/moko.co.ke/wp-content/uploads/2024/08/HUM_9636-1-1-500x500.jpg', ARRAY['https://cdn.shortpixel.ai/spai/w_433+q_lossy+ret_img+to_webp/moko.co.ke/wp-content/uploads/2024/08/HUM_9636-1-1-500x500.jpg'], 'TV Stands', 'Extra large modern TV stand accommodating up to 85-inch screens. Ultimate solution for large entertainment setups.', ARRAY['Extra large design', 'Premium materials', 'Advanced features', 'Ultimate storage', 'Luxury finish'], ARRAY['Width: 2100mm', 'Height: 500mm', 'Depth: 400mm'], ARRAY['Extra large design', 'Ultimate storage', 'Premium materials', 'Luxury finish'], ARRAY['modern-tv-stand-75-inch', 'modern-tv-stand-65-inch', 'modern-tv-stand-55-inch']);

-- ============================================================================
-- Migration Complete
-- ============================================================================
SELECT 'Migration completed successfully!' AS status,
       COUNT(*) AS total_products,
       COUNT(CASE WHEN category = 'Sofas' THEN 1 END) AS sofas_count,
       COUNT(CASE WHEN category = 'Mattresses' THEN 1 END) AS mattresses_count,
       COUNT(CASE WHEN category = 'Beds' THEN 1 END) AS beds_count,
       COUNT(CASE WHEN category = 'Carpets' THEN 1 END) AS carpets_count,
       COUNT(CASE WHEN category = 'TV Stands' THEN 1 END) AS tvstands_count
FROM products;
